name: build-book

on:
  workflow_call:

env:
  # the BASE_URL environment variable needs to be set if building with myst
  BASE_URL: "/${{ github.event.repository.name }}"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - name: Test for environment change
        id: env_change
        uses: tj-actions/changed-files@v47
        with:
          files: environment.yml

      - name: Echo environment change test result
        run: |
          echo '(DEBUG) The value of steps.env_change.outputs.any_changed is:'
          echo ${{ steps.env_change.outputs.any_changed }}

      - name: Setup environment with micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml

      - name: Check for myst.yml tags
        id: myst-tags
        run: |
          yq '.project.tags | filter(test("^foo:"))[] | sub("foo:(.*)","$1=1")' | tee "$GITHUB_OUTPUT"

      - name: Setup execution environment on a BinderHub
        if: steps.myst-tags.outputs.build-on-binder
        # This action sets up evironment variables for e.g. mystmd to recognise and use
        uses: 2i2c-org/clinder@action-v1
        with:
          hub-url: https://binder.projectpythia.org/

      - name: Cache execution
        if: "!steps.myst-tags.outputs.build-on-binder"
        uses: actions/cache@v4
        with:
          path: ${{ inputs.path_to_notebooks }}/_build/execute
          key: ${{ runner.os }}-${{ hashFiles(env.ENV_FILE) }}-execution

      - name: Build the book
        run: |
          # Allow custom build command
          if [[ -x "build.sh" ]]; then
            ./build.sh
          else
            myst build --execute --site --strict
          fi

      - name: Upload zipped AST artifact
        id: site-artifact
        uses: actions/upload-artifact@v6
        with:
          name: cookbook-ast
          path: _build/site/

      - name: Display build URL
        run: |
          # Use env for safer handling.
          echo "URL={{ steps.site-artifact.artifact-url }}" >> "$GITHUB_ENV"

          # Escape component
          python - <<- 'EOF' >> "$GITHUB_STEP_SUMMARY"
          import urllib.parse, os; 
          component = urllib.parse.quote(os.environ['URL'])
          print(f"Preview this build at https://https://jupyterbook.pub/repo/{component}")
          EOF
