name: config-validator

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}=${{ github.head_ref}}
  cancel-in-progress: true

jobs:
  myst-validator:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Validate workflows
        uses: dsanders11/json-schema-validate-action@v2.0.0
        with:
          # Assume that MyST schema is unchanging
          schema: https://raw.githubusercontent.com/ProjectPythia/cookbook-actions/refs/heads/feat/clinder/myst.schema.json
          files: myst.yaml
