name: find-pull-request

on:
  workflow_call:
    outputs:
      number:
        description: "The Pull Request number"
        value: ${{ jobs.find-pr.outputs.number }}
      sha:
        description: "The SHA of the commit associated with this PR"
        value: ${{ jobs.find-pr.outputs.sha }}

jobs:
  find-pr:
    runs-on: ubuntu-latest
    outputs:
      number: ${{ steps.find-pull-request.outputs.pullRequestNumber }}
      sha: ${{ steps.find-pull-request.outputs.mergeCommitSha }}
    steps:
      - name: Find Pull Request
        # uses: 8BitJonny/gh-get-current-pr@2.1.2
        # with:
        #   # Authetication token to access GitHub APIs. (Can be omitted by default.)
        #   github-token: ${{ github.token }}
        #   # Verbose setting SHA when using Pull_Request event trigger to fix #16. (For push even trigger this is not necessary.)
        #   # sha: ${{ github.sha }}
        # uses: actions/github-script@v6
        id: find-pull-request
        uses: potiuk/get-workflow-origin@v1_1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}
        # with:
        #   script: |
        #     let pullRequestNumber = ''
        #     let pullRequestHeadSHA = ''
        #     core.info('Finding pull request...')
        #     const pullRequests = await github.rest.pulls.list({owner: context.repo.owner, repo: context.repo.repo})
        #     for (let pullRequest of pullRequests.data) {
        #       if(pullRequest.head.sha === context.payload.workflow_run.head_commit.id) {
        #           pullRequestHeadSHA = pullRequest.head.sha
        #           pullRequestNumber = pullRequest.number
        #           break
        #       }
        #     }
        #     core.setOutput('number', pullRequestNumber)
        #     core.setOutput('sha', pullRequestHeadSHA)
        #     if(pullRequestNumber === '') {
        #       core.info(
        #          `No pull request associated with git commit SHA: ${context.payload.workflow_run.head_commit.id}`
        #       )
        #     }
        #     else{
        #       core.info(`Found pull request ${pullRequestNumber}, with head sha: ${pullRequestHeadSHA}`)
        #     }
     # This will echo "Your PR is 7", or be skipped if there is no current PR.
      - run: echo "Your PR is ${PR}"
        if: success() && steps.find-pull-request.outputs.pullRequestNumber
        env:
          PR: ${{ steps.find-pull-request.outputs.pullRequestNumber }}
