name: find-pull-request

on:
  workflow_call:
    outputs:
      number:
        description: "The Pull Request number"
        value: ${{ jobs.find-pr.outputs.number }}
      # sha:
      #   description: "The SHA of the commit associated with this PR"
      #   value: ${{ jobs.find-pr.outputs.sha }}

jobs:
  find-pr:
    runs-on: ubuntu-latest
    outputs:
      number: ${{ steps.find-pull-request.outputs.number }}
      # sha: ${{ steps.find-pull-request.outputs.sha }}
    steps:
      - name: Find Pull Request
        uses: jwalton/gh-find-current-pr@v1
        # uses: actions/github-script@v6
        id: find-pull-request
        # with:
        #   script: |
        #     let pullRequestNumber = ''
        #     let pullRequestHeadSHA = ''
        #     core.info('Finding pull request...')
        #     const pullRequests = await github.rest.pulls.list({owner: context.repo.owner, repo: context.repo.repo})
        #     for (let pullRequest of pullRequests.data) {
        #       if(pullRequest.head.sha === context.payload.workflow_run.head_commit.id) {
        #           pullRequestHeadSHA = pullRequest.head.sha
        #           pullRequestNumber = pullRequest.number
        #           break
        #       }
        #     }
        #     core.setOutput('number', pullRequestNumber)
        #     core.setOutput('sha', pullRequestHeadSHA)
        #     if(pullRequestNumber === '') {
        #       core.info(
        #          `No pull request associated with git commit SHA: ${context.payload.workflow_run.head_commit.id}`
        #       )
        #     }
        #     else{
        #       core.info(`Found pull request ${pullRequestNumber}, with head sha: ${pullRequestHeadSHA}`)
        #     }
     # This will echo "Your PR is 7", or be skipped if there is no current PR.
      - run: echo "Your PR is ${PR}"
        if: success() && steps.find-pull-request.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}
