name: preview-comment

on:
  workflow_call:
    inputs:
      pull_request_number:
        description: 'Number of the Pull Request event that needs commenting'
        required: true
        type: string
      sha:
        description: 'SHA of the commit associated with this Pull Request'
        required: true
        type: string
      site_name: 
        description: 'Name of the website in comment'
        required: false
        default: "The Cookbook"
        type: string

jobs:
  comment:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v6
      - name: Fetch Repo Name
        id: repo-name
        run: echo "value=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_OUTPUT  # just the repo name, not owner

      - name: Set message value
        run: |
          echo "comment_message=👋 Thanks for opening this PR! ${{ inputs.site_name }} will be automatically built with [GitHub Actions](https://github.com/features/actions). To see the status of your deployment, click below." >> $GITHUB_ENV

      - name: Find preview comment
        uses: peter-evans/find-comment@v4
        id: fc
        with:
          issue-number: '${{ inputs.pull_request_number }}'
          comment-author: 'github-actions[bot]'
          body-includes: '${{ env.comment_message }}'

      - name: Create preview comment
        if: |
          github.event.workflow_run.conclusion != 'success'
          && steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ inputs.pull_request_number }}
          body: |
            ${{ env.comment_message }}
            🔍 Git commit SHA: ${{ inputs.sha }}
            ✅ Deployment Preview URL: In Progress

      - name: Update preview comment
        if: |
          github.event.workflow_run.conclusion != 'success'
          && steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            ${{ env.comment_message }}
            🔍 Git commit SHA: ${{ inputs.sha }}
            ✅ Deployment Preview URL: In Progress

      - name: Stash the artifact URL
        env:
          GH_TOKEN: ${{ github.token }}

        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            /repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts \
            -q '"SITE_URL=\(.artifacts | map(select(.name == "site"))[0].url)"' >> "$GITHUB_ENV"

      - name: Set preview URL
        if: |
          github.event.workflow_run.conclusion == 'success'
          && steps.fc.outputs.comment-id != ''
        id: preview-url
        run: |
          # Escape component
          import urllib.parse, os; 
          component = urllib.parse.quote_plus(os.environ['SITE_URL'])
          preview_url = f"https://hub.projectpythia.org/services/jupyterbook-pub/repo/{component}/"
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"url={preview_url}")
        shell: python {0}

      - name: Finalize preview comment
        if: |
          github.event.workflow_run.conclusion == 'success'
          && steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            ${{ env.comment_message }}
            🔍 Git commit SHA: ${{ inputs.sha }}
            ✅ Deployment Preview URL: ${{ steps.preview-url.outputs.url }}

