name: trigger-template-build
on:
  pull_request:

jobs:
  get-code:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ProjectPythiaCookbooks/cookbook-template

  build:
    uses: ProjectPythiaCookbooks/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name: cookbook-dev
      environment_file: environment.yml
      path_to_notebooks: ./
      use_cached_environment: 'true'  # This is default, not strickly needed. Set to 'false' to always build a new environment
      